### ISSUE TITLE
"Replace 'runserver.py' with 'pythoncz run'" nefunguje na produkci

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/python.cz#236]
PR https://github.com/pyvec/python.cz/pull/227 shodí produkci s následující chybovou hláškou v logu:

```
[2017-10-05 17:02:26 +0200] [3491] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/srv/venv/lib/python3.4/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/srv/venv/lib/python3.4/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/srv/venv/lib/python3.4/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/srv/venv/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/srv/venv/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/srv/venv/lib/python3.4/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
ImportError: No module named 'app'
Traceback (most recent call last):
  File "/srv/venv/lib/python3.4/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/srv/venv/lib/python3.4/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/srv/venv/lib/python3.4/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/srv/venv/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/srv/venv/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/srv/venv/lib/python3.4/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
ImportError: No module named 'app'
[2017-10-05 17:02:26 +0200] [3491] [INFO] Worker exiting (pid: 3491)
```

Když jsem zkusil na produkčním serveru rozjet gunicorn ručně, musel jsem akorát všude v modelech doplnit `open(..., encoding='utf-8')`, jinak to jelo. Přes supervisord to nejede.

Proč to nejede a proč bylo pro ruční spuštění potřeba nastavit kódování souborů, ačkoliv předtím to nevadilo, tomu nerozumím. Pokud by měl někdo chuť na tom pracovat, vycházejte z větve `shared/package`.

**Comment by frenzymadness** [comment]
Přidávám, že když je v `runserver.py` nastaven `app.config['SERVER_NAME']`, tak lokálně spuštěný web nefunguje a na jakýkoli dotaz vrací 404.

Pravděpodobně je to proto, že `SERVER_NAME` je nastaven na `0.0.0.0:5000`, ale navštěvovaná URL je `http://127.0.0.1:5000/`.

Pokud je ale cílem se `runserver.py` zbavit, není třeba to řešit.

**Comment by honzajavorek** [comment]
I believe this is not relevant anymore, the site is now a static page.
