### ISSUE TITLE
Podpora pro Python 2.X nebo alespoň dokumentace podporovaných verzí

### ISSUE THREAD

**Issue by martinbilek** [pyvec/python.cz#86]
Když si nainstaluji python.cz dle návodu, tak mi aplikace nelze spustit na OSX s následující chybou:
```
(python.cz)Martins-MBP:python.cz semik$ python runserver.py
Traceback (most recent call last):
  File "runserver.py", line 7, in <module>
    from pythoncz import app
  File "/Users/semik/workspace/python.cz/pythoncz/__init__.py", line 28, in <module>
    from . import views  # NOQA
  File "/Users/semik/workspace/python.cz/pythoncz/views.py", line 8, in <module>
    from .models import trello, jobs, photos, beginners
  File "/Users/semik/workspace/python.cz/pythoncz/models/jobs.py", line 63, in <module>
    data['job_boards'] = _sort_cs(data['job_boards'])
  File "/Users/semik/workspace/python.cz/pythoncz/models/jobs.py", line 51, in _sort_cs
    return sorted(iterable, key=item_key)
  File "/Users/semik/workspace/python.cz/pythoncz/models/jobs.py", line 50, in item_key
    return czech_sort.key(item[key])
  File "/Users/semik/.virtualenvs/python.cz/lib/python2.7/site-packages/czech_sort/impl.py", line 95, in key
    normal = nfkd(lowercased)
TypeError: must be unicode, not str
```

**Comment by encukou** [comment]
Workaround je použít Python 3.

`czech_sort` umí jen unicode – by design.

**Comment by honzajavorek** [comment]
Psal jsem to v Python 3, ale už si nepamatuju, jestli jsem chtěl mít i podporu pro Python 2 (dávalo by to smysl kvůli contributions). Každopádně je to chyba, protože i kdyby to bylo Python 3 -only, tak ses to neměl kde dovědět - není to nikde zdokumentováno :disappointed:

**Comment by honzajavorek** [comment]
Hm! Tohle je ale zajímavé - https://github.com/pyvec/python.cz/blob/master/.travis.yml#L2:L6 Podle Travisu by to tedy mělo jet všude. Máme chybu v testech?
